# Generated by Django 4.1.7 on 2023-04-05 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_roommember"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="online_user_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_room_set",
                through="chat.RoomMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
